"""
neural_collision_checker.py — Inference wrapper for the PointNet collision detector.

Drop-in replacement for the geometric collision checker used in RRT-Connect.
Your planner only needs to call:

    checker = NeuralCollisionChecker("checkpoints/collision_model.pt", scene_point_cloud)
    is_col  = checker.in_collision(config)          # single config
    mask    = checker.batch_in_collision(configs)   # many configs at once

Location: src/planner/neural_collision_checker.py

Design notes
------------
* Keeps the model + scene point cloud on GPU (or CPU if no GPU).
* The scene point cloud is normalised once at load time and cached as a tensor
  that is broadcast across a whole batch — zero repeated computation.
* batch_in_collision() is ~100-1000x faster than calling in_collision() in a
  loop and is the preferred API for RRT-Connect's steering / neighbour checks.
* Threshold is tunable; default 0.5 corresponds to the raw sigmoid probability.
  Raise it (e.g. 0.3) to be more conservative (fewer false free-space calls).
"""

import os
import sys
from pathlib import Path
from typing import List, Union

import numpy as np
import torch
import torch.nn.functional as F

from collision_detector import JOINT_LIMITS

# Allow running as a standalone script or imported from src/
_SCRIPT_DIR = Path(__file__).resolve().parent
_SRC_DIR    = _SCRIPT_DIR.parent
if str(_SRC_DIR) not in sys.path:
    sys.path.insert(0, str(_SRC_DIR))

from model.model import PointNetCollisionDetector


# ──────────────────────────────────────────────
# Joint limits (must match generate_dataset.py / collision_detector.py)
# ──────────────────────────────────────────────

_JOINT_LOWER = np.array([lo for lo, _ in JOINT_LIMITS], dtype=np.float32)
_JOINT_UPPER = np.array([hi for _, hi in JOINT_LIMITS], dtype=np.float32)
_JOINT_RANGE = _JOINT_UPPER - _JOINT_LOWER


def _normalize_config(config: np.ndarray) -> np.ndarray:
    """Normalise a config array to [-1, 1] — must match training."""
    return 2.0 * (config - _JOINT_LOWER) / _JOINT_RANGE - 1.0


def _normalize_point_cloud(points: np.ndarray) -> np.ndarray:
    """Centre and scale point cloud to unit sphere — must match dataset.py."""
    centroid = points.mean(axis=0)
    pts      = points - centroid
    max_dist = np.max(np.linalg.norm(pts, axis=1))
    if max_dist > 0:
        pts = pts / max_dist
    return pts.astype(np.float32)


# ──────────────────────────────────────────────
# Main class
# ──────────────────────────────────────────────

class NeuralCollisionChecker:
    """PointNet-based collision checker for a single scene.

    Parameters
    ----------
    model_path : str
        Path to the saved inference model (output of train.py).
    scene_point_cloud : np.ndarray  shape (N, 3)
        Raw obstacle surface point cloud for the current scene.
        Can be generated by generate_dataset.py's extract_scene_point_cloud().
    n_points : int
        Number of points to sub-sample from the cloud (default: 2048).
    threshold : float
        Sigmoid probability threshold above which a config is "in collision"
        (default: 0.5).  Lower values → more conservative (safer).
    device : str or None
        Force a specific device string ('cpu', 'cuda', 'mps').
        If None, auto-selects the best available device.
    batch_size : int
        Internal batch size for batch_in_collision() (default: 512).
    """

    def __init__(
        self,
        scene_point_cloud: np.ndarray,
        model_path: str = '../model/checkpoints/best.pt',
        n_points:   int   = 2048,
        threshold:  float = 0.5,
        device:     str | None = None,
        batch_size: int   = 512,
    ):
        # ── Device ────────────────────────────
        if device is None:
            if torch.cuda.is_available():
                device = "cuda"
            elif torch.backends.mps.is_available():
                device = "mps"
            else:
                device = "cpu"
        self.device     = torch.device(device)
        self.threshold  = threshold
        self.batch_size = batch_size
        self.n_points   = n_points

        # ── Load model ────────────────────────
        ckpt       = torch.load(model_path, map_location="cpu")
        model_cfg  = ckpt["model_cfg"]
        self.model = PointNetCollisionDetector(**model_cfg)
        self.model.load_state_dict(ckpt["model_state"])
        self.model.to(self.device)
        self.model.eval()
        print(f"[NeuralCollisionChecker] Loaded model from {model_path}")
        print(f"  Device    : {self.device}")
        print(f"  Threshold : {self.threshold}")

        # ── Pre-process scene point cloud ─────
        self._pc_tensor = self._prepare_point_cloud(scene_point_cloud)
        # shape: (1, n_points, 3) on device — broadcast over batches

    # ─────────────────────────────────────────
    # Public API
    # ─────────────────────────────────────────

    def update_scene(self, scene_point_cloud: np.ndarray) -> None:
        """Swap the cached scene; call this when the RRT moves to a new env."""
        self._pc_tensor = self._prepare_point_cloud(scene_point_cloud)

    def in_collision(self, config: Union[List[float], np.ndarray]) -> bool:
        """Check a single configuration.

        Returns True if the model predicts a collision.
        """
        config_arr = np.asarray(config, dtype=np.float32).reshape(1, 7)
        mask       = self._run(config_arr)
        return bool(mask[0])

    def collision_probability(self, config: Union[List[float], np.ndarray]) -> float:
        """Return the raw sigmoid collision probability for a single config."""
        config_arr = np.asarray(config, dtype=np.float32).reshape(1, 7)
        probs      = self._run_probs(config_arr)
        return float(probs[0])

    def batch_in_collision(
        self, configs: Union[List[List[float]], np.ndarray]
    ) -> np.ndarray:
        """Check a batch of configurations at once (much faster than looping).

        Parameters
        ----------
        configs : array-like, shape (M, 7)

        Returns
        -------
        mask : np.ndarray bool, shape (M,)
            mask[i] is True if configs[i] is predicted to be in collision.
        """
        configs_arr = np.asarray(configs, dtype=np.float32)
        if configs_arr.ndim == 1:
            configs_arr = configs_arr[None, :]
        return self._run(configs_arr)

    def batch_collision_probabilities(
        self, configs: Union[List[List[float]], np.ndarray]
    ) -> np.ndarray:
        """Return sigmoid probabilities for a batch of configs."""
        configs_arr = np.asarray(configs, dtype=np.float32)
        if configs_arr.ndim == 1:
            configs_arr = configs_arr[None, :]
        return self._run_probs(configs_arr)

    # ─────────────────────────────────────────
    # Internal helpers
    # ─────────────────────────────────────────

    def _prepare_point_cloud(self, raw_pc: np.ndarray) -> torch.Tensor:
        """Normalise and sub-sample, return (1, n_points, 3) on device."""
        pts = _normalize_point_cloud(raw_pc)
        n   = len(pts)
        if n >= self.n_points:
            idx = np.random.choice(n, self.n_points, replace=False)
        else:
            idx = np.random.choice(n, self.n_points, replace=True)
        pts = pts[idx]  # (n_points, 3)
        return torch.from_numpy(pts).unsqueeze(0).to(self.device)  # (1, n_points, 3)

    @torch.no_grad()
    def _run(self, configs_arr: np.ndarray) -> np.ndarray:
        probs = self._run_probs(configs_arr)
        return probs >= self.threshold

    @torch.no_grad()
    def _run_probs(self, configs_arr: np.ndarray) -> np.ndarray:
        M       = len(configs_arr)
        all_p   = []
        pc_base = self._pc_tensor  # (1, n_points, 3)

        for start in range(0, M, self.batch_size):
            end     = min(start + self.batch_size, M)
            chunk   = configs_arr[start:end]               # (B, 7)

            # Normalise configs exactly as done during training
            chunk_n = _normalize_config(chunk)
            cfg_t   = torch.from_numpy(chunk_n).to(self.device)   # (B, 7)

            # Broadcast point cloud: (1, n, 3) → (B, n, 3)
            pc_t    = pc_base.expand(len(chunk), -1, -1)

            logits, _ = self.model(pc_t, cfg_t)            # (B,)
            probs     = torch.sigmoid(logits).cpu().numpy()
            all_p.append(probs)

        return np.concatenate(all_p, axis=0)


# ──────────────────────────────────────────────
# Quick smoke-test
# ──────────────────────────────────────────────

if __name__ == "__main__":
    import argparse

    ap = argparse.ArgumentParser()
    ap.add_argument("--model",  required=True, help="Path to collision_model.pt")
    ap.add_argument("--n-configs", type=int, default=1000,
                    help="Number of random configs to test (throughput benchmark)")
    args = ap.parse_args()

    # Fake point cloud (replace with your real scene cloud)
    rng    = np.random.default_rng(0)
    fake_pc = rng.uniform(-1, 1, (2048, 3)).astype(np.float32)

    checker = NeuralCollisionChecker(
        model_path=args.model,
        scene_point_cloud=fake_pc,
    )

    # Single-config API
    cfg = rng.uniform(_JOINT_LOWER, _JOINT_UPPER, 7).astype(np.float32)
    print(f"\nSingle config collision: {checker.in_collision(cfg)}")
    print(f"Collision probability : {checker.collision_probability(cfg):.4f}")

    # Batch API + throughput
    configs = rng.uniform(_JOINT_LOWER, _JOINT_UPPER, (args.n_configs, 7)).astype(np.float32)

    import time
    t0   = time.time()
    mask = checker.batch_in_collision(configs)
    dt   = time.time() - t0

    print(f"\nBatch of {args.n_configs} configs:")
    print(f"  Predicted collisions : {mask.sum()} ({mask.mean()*100:.1f}%)")
    print(f"  Elapsed              : {dt*1000:.1f} ms")
    print(f"  Throughput           : {args.n_configs/dt:,.0f} configs/s")
